### ISSUE TITLE
No Silent's mining level 3 pick

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#1]
The recent change to inhibit early game flight has left the pack without a Silent's gems pick to mine obsidian until after reaching the end.

The progression is Flint (ironic as the pack claims to avoid that), Some normal gem pick (mining level 2) which as far as I can see you need a vanilla iron pick or some other mods equivalent to get these gems. Silent's seems to skip mining level 3 straight to the super gems at level 4(cobalt).   

I was able to use all vanilla methods to get to the end and avoid the dragon long enough to collect what I needed early game. Took a few hours to rush flight this time, but having to use a vanilla nerfed diamond pick to get obsidian early on is a pain.

**Comment by superfluke** [comment]
Check out the diamond tip upgrade for silents gems. I'll leave this open so I remember to add silents gems quests to the quest book.

**Comment by Ozzymud** [comment]
Whelp, there we go, didn't know that existed :) Consider it closed when your done with the reminder :)
