### ISSUE TITLE
Using a bucket on a DNA Etractor returns empty bucket - no DNA

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#10]
Finally got enough power and drones to make 1000mb of Liquid DNA. Used an empty bucket on the machine and it destroyed the Liquid DNA. Machine and bucket were empty. Thought maybe a desync issue so saved/quit/reloaded.. bucket and machine still empty.

**Comment by superfluke** [comment]
Well that's a fun bug. Reported to gendustry and changed the recipe over to a can of DNA which works fine when right clicked on the DNA extractor.
