### ISSUE TITLE
Itemduct (Opaque) - Magneticraft Lead

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#11]
Magneticraft lead doesn't work to create itemducts, the script doesn't use oreLead but specifies the Thermal Expansion lead. The magneticraft lead can be turned into nuggets then re-crafted into Thermal lead.

**Comment by superfluke** [comment]
Fixed next update. All chunks/crushed stuff from magneticraft should also now smelt to the same ingot type as world gen ores do.
