### ISSUE TITLE
Compressed Slime Block Isn't Harvestable

### ISSUE THREAD

**Issue by 6mjo9** [superfluke/undiscovered#12]
Breaking a compressed slime block yields a regular slime block with or without silk touch.

**Comment by Ozzymud** [comment]
I wouldn't think it was intended to. It's like trying to pick up farmland, it reverts to dirt regardless of silk touch.

**Comment by superfluke** [comment]
Hmm, yeah seems like it can't be harvested. Added some alternative recipes in the next update.
