### ISSUE TITLE
Silent's Gems enchantment tokens - all modded tokens uncraftable

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#13]
Enchantment tokens for any enchant that is from a mod do not have a recipe. Dunno if this is a bug with Siltent's Gems or not. Can always minetweak recipes in for those tokens.

Affected tokens - 

- Random Things: Magnetic
- EvilCraft: Vengence, Unusing, Breaking, Poison Tip
- CofH Core: Holding, Multishot, Vorpal, Leech, Smelting, Insight
- BiblioCraft: Eternal Compass, Reading
- Astral Sorcery: Night Vision, Scorching Heat
- Draconic Evolution: Reaper
- Extra Utilities 2: Bladerang, Boomereaperang, Burnerang, Kaboomerang, Zoomerang

I think that's all of them. Vanilla and Silent's enchants are all craftable.

**Comment by superfluke** [comment]
Interesting, I'll have to look into some of those enchantments more since I don't know what all of those do. Probably not next update but the one after that all either add recipes or hide them.

**Comment by Ozzymud** [comment]
Further research shows an issue on Silent's side of it, it is an open issue over there as well, looks like they will be added soon though. Still, shouldn't be tough to come up with some pack-centric recipes anyways.

**Comment by superfluke** [comment]
Added as dungeon/lost city/temple loot
