### ISSUE TITLE
Useless dust from stone seperator

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#14]
Small Stone(dustStone) needs a use. It is piling up quite quickly from the stone seperator. Suggest at least adding a recipe to make 4 dust = 1 stone(smooth). The only 2 usages for it currently are as a 2 heart projectile weapon (useless with silents bows), and to hoe grass into farmland (again pretty useless).

**Comment by superfluke** [comment]
Added a recipe, but it can also be used to turn dirt to gravel.
