### ISSUE TITLE
Open Blocks Is Out

### ISSUE THREAD

**Issue by JakeOTwitch** [superfluke/undiscovered#16]
Not really and "issue", but open block has just been updated... that is all. (P.S Loving your pack, thanks for being so active in the github)

**Comment by superfluke** [comment]
Neat, there are quite a few mods in the pack based on old open block items, so I'll have to checkout if its worth replacing those with open blocks or not.

**Comment by Ozzymud** [comment]
My 2 cents... it is :P The replacements are a shell of the former items.

**Comment by superfluke** [comment]
Probably not going to be switching over to open blocks. While I do miss some stuff like the graves/player inventory command and dev/null, overall the mod has lots of features that are duplicated by other mods where I prefer the other mods. 
Open gliders lets me adjust a bunch of speed/wind configs, comforts has the hammock for day naps (super nice with AS), elevator replacement is fine, breaker/placer is added by multiple mods already, auto enchanter can be done with arcane ensorcellator, auto anvil can be done with blood chest. Also don't like some of the balance issues enchaments like flim flam and last stand bring, along with silly things like pork farms made with mob trophies. And while I get the love for the OB fan over mob grinding utils, I like the grider + enchantments and GM chicken feed that mob grinding utils adds more than I like the easier to use fan.
