### ISSUE TITLE
A Fancier Torch Quest

### ISSUE THREAD

**Issue by JakeOTwitch** [superfluke/undiscovered#17]
Quest #229: A Fancier Torch says Only 1 task needed to complete quest but requires all 3 to be complete

**Comment by Ozzymud** [comment]
Can confirm:

![image](https://user-images.githubusercontent.com/6426344/34122820-7feabbde-e3e2-11e7-94e2-b3c1ef3545c7.png)

**Comment by superfluke** [comment]
Fixed in update
