### ISSUE TITLE
CofH Mana Infused ore (oreMithril) not generating

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#19]
Thus far I haven't found any. Looked at the cofh world config files and I don't see it in there. It doesn't generate by default and must be added in modpacks. See: https://teamcofh.com/docs/mana-infused-ore/  

I added the following to my 01_thermalfoundation_ores.json: (this is basically like redstone)
```
		"mithril": {
			"distribution": "uniform",
			"generator": {
				"block": {
					"name": "thermalfoundation:ore",
					"metadata": 8
				},
				"material": "minecraft:stone",
				"cluster-size": 4
			},
			"cluster-count": 1,
			"min-height": 1,
			"max-height": 16,
			"retrogen": "true",
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},
```
After adding I went back down to my y:6 redstone mine and found:
![image](https://user-images.githubusercontent.com/6426344/34120950-3efce10c-e3dc-11e7-9eea-6ed856f55e8b.png)

**Comment by superfluke** [comment]
Mana infused ore should not generate. This is intended.

**Comment by Ozzymud** [comment]
There is no way to get it and it is needed in some recipes (the ingot)

**Comment by superfluke** [comment]
There are recipes for the ingot which involve molten mithril. Check the quest book if you get lost in progression.

**Comment by Ozzymud** [comment]
I've almost given up on the quest book, I'm not one for quests just to quest, and a lot of the things that need to be crafted for the quests are pretty useless. Besides, it was a neat twist earlier game.. but the whole vodka, starlight many steps to get something like that now leaves a bad taste in my mouth. I love the anvil/sluice thing, that's unique. But some of these methods are just too wierd for what seems like the sake of wierdness. Thought I found a good pack here and was trying to be vested in it.. oh well, off to find another pack. Laters...
