### ISSUE TITLE
Alchemic Condenser/Retort (3. No one use machines.)

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#2]
The pack claims to not have me craft a machine I will use once and then toss in a chest. The Advanced Alchemic machines can do everything that the normal one does. Suggest using the old parts in the recipes for the advanced ones. Also the advanced takes 3 retorts, having the player only craft 2 for the quest kinda stumped me and i had to leave the game to check online what was wrong.

**Comment by superfluke** [comment]
I like the idea for the new crafting recipes. Changed in next update. Quest fixed to show proper number of retorts.
