### ISSUE TITLE
Bottling Machine Can't be Made

### ISSUE THREAD

**Issue by JakeOTwitch** [superfluke/undiscovered#20]
Right clicking on the conveyor belt to convert the multiblock into a bottling machine only turns the conveyor belt, it does not convert it.

**Comment by Ozzymud** [comment]
Cannot confirm, formed for me:
![image](https://user-images.githubusercontent.com/6426344/34123712-41ceab32-e3e5-11e7-905c-a8104498ea2a.png)

Ensure the conveyors are moving in the right direction and the rest of the structure is ok.

**Comment by JakeOTwitch** [comment]
I will try building it again, I did attempt it with the conveyors moving both ways.

**Comment by JakeOTwitch** [comment]
This was my fault, the glass did not appear in the Bottling Machine Projector... Woops
