### ISSUE TITLE
Creative watering can defective

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#21]
Just made the creative watering can, went out harvested my wheat, tryed to use the can (after adding water to it) to grow the crops... didn't seem to do anything, not even water particles. It also claims to hydrate farm land, so I went away from water and hoed some land, used the can again, the farmland remained un-hydrated.  

Edit: also switched to creative in case it somehow only worked in creative mode.. still nothing.

![image](https://user-images.githubusercontent.com/6426344/34122648-07663ee0-e3e2-11e7-8d4e-c9c292949814.png)

**Comment by superfluke** [comment]
Fixed in update
