### ISSUE TITLE
Empowered enori recipe needs exact thermal tin ingot - please oredict

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#23]
The recipe only accepts the thermal foundation ingot, the means given normal produce another mods ingot. Can work around by crafting to nuggets, then back to an ingot using recipe conflict mod to choose thermal... that's annoying though.

**Comment by superfluke** [comment]
Empowerer won't take oredict for its recipes but mek ore should smelt to TE ingot now like other tin sources do.
