### ISSUE TITLE
Quest rewards?

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#3]
There doesn't seem to be any rewards for completing quests. Knowing this from my 1st map, I didn't even open the quest book until well into making steel. Thus I had to tear down several machines just to get the quest to complete. Having some incentive, however small, would entice me to actually use the quest book. Punching wood... give some sticks, more wood, flint... something, nothing OP or amazing. unless the quest is one of the make this, you might not ever use it as there is better items, like the container quest, I had acquired over a stack of chests by the time that quest was a thing.

**Comment by superfluke** [comment]
Only took 3 months :p
