### ISSUE TITLE
Crafting Basic Gas Tank Credits Creative Gas Tank

### ISSUE THREAD

**Issue by SpoonieTheBard** [superfluke/undiscovered#32]
I don't know exactly what triggered it, but I was crafting basic gas tanks, and on the fourth or fifth one, I randomly got credited for the Creative Gas Tank.  I am playing on the JakeO sub server (which has RS installed).  Not sure if RS would impact it, and I'm not sure why it was the fourth or fifth craft that gave me credit for it.  Posting just in case.

**Comment by SpoonieTheBard** [comment]
Later, gave me credit for creative fluid tank when creating the basic fluid tank.

**Comment by superfluke** [comment]
Should detect properly in update
