### ISSUE TITLE
Suggestion: Chiseled block oredict with customized crafts

### ISSUE THREAD

**Issue by SpoonieTheBard** [superfluke/undiscovered#33]
I know that chisel is having a few issues, and I cannot claim to know what that's about, but I saw that some recipes work for chiseled glowstone as if it treats it as regular glowstone.  Would it be possible to oredictionary these chiseled glowstone to work in the custom recipes you've created?

**Comment by superfluke** [comment]
Sure, I can do that. Changed over to ore dict in the few custom recipes that use glowstone. The AA empowerer will still take normal glowstone since it's allergic to oredicts.
