### ISSUE TITLE
Sky stone dust

### ISSUE THREAD

**Issue by jinkhya** [superfluke/undiscovered#36]
Hello, 
I can't make the skystone dust with the crushing table(magneticraft). Using the Iron hammer on the sky stone doesn't do anything.
Jin

**Comment by superfluke** [comment]
Try upgrading to a steel hammer

**Comment by jinkhya** [comment]
Ah yeah that worked thank you very much ! too bad Jei doesn't show wich hammer is needed.

**Comment by superfluke** [comment]
No problem, I'm gonna leave it open so I remember to add a jei info blurb on skystone dust. You're not the first person I've seen get tripped up on this step

**Comment by jinkhya** [comment]
No worries, thanks for your awesome work \o/
