### ISSUE TITLE
Lost cities "default" profile

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#4]
The quest book seems to prefer I stay away from the cities. However, the default settings if I just click "create world" have the default generator as Lost Cities and it by default uses the "default" profile, which pretty much makes the world an endless city with only small areas here and there lacking some sort of structure. Even choosing to customize the world and choosing the "rare" profile for Lost Cities has them appear quite frequently, 4 new maps so far and I gave up as each one started me within view of a city. 3 so far have placed me IN a city staring at a building at spawn.

**Comment by superfluke** [comment]
A mod is included that sets the default world type to Lost Cities with the rare cities profile. Just installed a fresh version of the pack and it still works properly for me. Even after creating a world with different setting, I'm still defaulted to rare cities when making a new world. If you are defaulting to the "default" profile in lost cities when creating a new world this may be a bug with the Default World Gen mod, but I can't reproduce it. 

Finding iron/furnaces that allow for skipping some early progression in lost cities is known and the quest book had been adjusted to account for that.

**Comment by Ozzymud** [comment]
Even with the "rare" profile, they appear about 20 times more often then vanilla cities. Like I said, it took 4 tries before I could even find a world where I at least didn't spawn IN a city.
