### ISSUE TITLE
Solegnolia (Botania) Not suppressing Ring of Magnetization

### ISSUE THREAD

**Issue by SpoonieTheBard** [superfluke/undiscovered#41]
The flower that is designed to suppress the ring of magnetization is not working.  Likely just a issue purely with Botania, but posting just in case it's not.

**Comment by superfluke** [comment]
I can't reproduce this in my world. If you can manage to find a way to reliably reproduce this or capture a gif of it happening, you might have better luck reporting it to the botania github.
