### ISSUE TITLE
Mod suggestion: rftools  control

### ISSUE THREAD

**Issue by Vauxite** [superfluke/undiscovered#43]
**Mod:**
https://minecraft.curseforge.com/projects/rftools-control

**Why:**
To automate all those weird but neat processes. I just started with the pack and afaik it won't add much if any redundancy.

In terms of additional work, shouldn't be much as the core component in RFtools has already been changed. Can't speak for number balance.

**Comment by superfluke** [comment]
I honestly haven't played with this mod too much. What do you think rftools control does that xnet or the various crafters provided cannot?

**Comment by MainFreak** [comment]
It can be used with Xnet but has no item transfer in itself afaik. It's like Integrated Dynamics with Autocrafting iirc.

**Comment by Vauxite** [comment]
@MainFreak It can transfer item and control a bunch stuff.

I believe xnet will do for this playthrough. I'll add it myself if I find xnet lacking in some regard.
