### ISSUE TITLE
Better than Potions (#180)

### ISSUE THREAD

**Issue by SpoonieTheBard** [superfluke/undiscovered#44]
The Rustic potions just say "Elixir of" without any specifics.  I know it was working in previous versions, but this quest seems to have changed.

**Comment by SpoonieTheBard** [comment]
I recall that one of the potions was Instant Health.  This is not working with this question any longer.

**Comment by superfluke** [comment]
Honestly, I have no idea what the hell is going on with these quest's nbt anymore. Sometimes the cryptic way bqm saves them works, sometimes it totally breaks. You'll probably find more of these screwy nbt quests as you go, so please do report them or just throw them in a comment here. I'll try poking around with the bqm data and pray that either hqm or bqm actually gets an update
