### ISSUE TITLE
Suggestion:  Not have Botania require inverted potentia

### ISSUE THREAD

**Issue by SpoonieTheBard** [superfluke/undiscovered#48]
I'm essentially waiting for rain to be able to start botania.  So, I'm waiting on a random event to be able to progress.  Not exactly the most exciting of things.  Maybe something else or even just the inverted potential core is fine itself, just don't need to empower it.

**Comment by superfluke** [comment]
I agree just waiting for weather would be a bad mechanic. However, there are a couple items that can create the empowered potentia without waiting. You can strike inverted potentia with lightning using the psi smite spell without even needing an environmental accumulator. You can also use the Evilcraft Sceptre of Thunder to change the weather to thunder and throw the inverted potentia into an environmental accumulator. 
Added this info to a jei tab for empowered potentia.
