### ISSUE TITLE
Uncraftable items, in spite of recipes

### ISSUE THREAD

**Issue by Thornstromb** [superfluke/undiscovered#49]
As Title says. specifically:
Silent's Gems Manual: This one isn't on your end, last pack we played with this mod it was uncraftable as well.
More importantly,
Evilcraft Blood Extractor. yep. recipe shows in JEI. placing items in a crafting grid shows 1 on the "how many to take button". output slot is empty. No amount of adjustment will work.

EDIT: what the??? the Evilcraft Blood Infuser is also uncraftable!
And the Thermalilly wont craft, even though the apothecary shows it correctly and asks for seeds.

that's... pretty much all.
oh: Undiscovered 2.1.0 via Twitch client

**Comment by superfluke** [comment]
I do not having any of these issues on my game. Just tried reinstalling from curse and loading a new world to double check, but no problems there either. I know curse was recently moving servers, so is possible the pack did not installed properly which is messing up your crafting. Try reinstalling the pack and let me know if you still have these issues

**Comment by Thornstromb** [comment]
WHELP. go ahead and close this issue.
looks like i have to talk to my server host (a freind).... its definitely on the serverside. an SP attempt had ALL of the mentioned items craft perfectly.

**Comment by superfluke** [comment]
Make sure the /scripts folder exists on the server, which might be the cause of this issue.
