### ISSUE TITLE
Getting tired of the same old expert progression. Make flint tools?

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#5]
Yes, yes I am, but the logical starter tools in this pack with the nerf to vanilla tools is Silent's Gems flint tools/weapons.  

Suggest adding Silent's Gems: Extra Parts (https://minecraft.curseforge.com/projects/silents-gems-extra-parts). This mod supports many of the mods in this pack: Vanilla alternatives (polished wood/stone), Botania, Calculator, Thermal Expansion/Immersive. 

This would likely solve issue #1 as I believe steel and some of the others can mine obsidian+. This would also allow completely nerfing vanilla and setting their durability to one(1).

**Comment by superfluke** [comment]
While I appreciate some more interesting tools, I find extra parts to be a bit excessive in the items its add for very little variation in the actual tools. Flint tools aren't any more needed than wooden tools and are only required to grab the few cobble needed to make stone tools.

**Comment by Ozzymud** [comment]
Why would I want to downgrade to stone (pick durability 50, iron level) after I have flint tools (silent flint durability 128 iron level)? Flint tools are really the only viable option early game, and even well into mid game now that I know of the diamond tip upgrade I really have no "need" to upgrade past flint making the pick as linear as Tinkers' tools.
