### ISSUE TITLE
Recipes for Unmakeable Machinery?

### ISSUE THREAD

**Issue by Thornstromb** [superfluke/undiscovered#50]
this is a suggestion/possibility/canthisbedone:
If possible, can the entire recipe lists for machines that can't be crafted (like the Redstone Furnace from Thermal Expansion) be deleted post-recipe generation? It's quite annoying to go looking for ways to process ore for example, and get lost in three different machines (with unaltered output recipes) that you can't actually make. If the recipes cannot be deleted outright, then maybe tweak all of said recipes to output a special item that basically exists just to say this machine doesn't exist, filling in the auto-generated recipes.

**Comment by superfluke** [comment]
I don't think that's possible atm. Mezz had mentioned adding an api to remove those machine tabs but it doesn't look like it ever got created. I might be able to bulk remove some of the stuff from the removed machines, I'll have to look into that more.

**Comment by superfluke** [comment]
Not perfect but removed a lot of ores and dusts from the redstone furnace and exu crusher. At least they will pop up less when looking up ore processing in jei. Nothing I can do about the exu furnace recipes.
