### ISSUE TITLE
Dynamo Tiers? Augments?

### ISSUE THREAD

**Issue by Thornstromb** [superfluke/undiscovered#52]
is it intentional that you cannot upgrade TE Dynamos? Due to this fact, you cannot ever apply dynamo Augments (they all require hardened tier). upgrader kits cannot be Used on dynamos, and there is no recipe to upgrade them (unlike certain machine blocks).

In addition, because they cannot be upgraded, they are permanently stuck at 50 RF/t. upgraded dynamo's have the same fuel economy, but have higher output rate (i forget the exact numbers). the dynamo's top output is strictly capped by it's tier, differing fuels merely extend operation time.

As an example of how insane this will get, a single DEPLETED IP Oil Pumpjack (output = 6mb/t for 800 rf/t) ran through two Fractioning Stills (10k RF per 200mb of Oil -> 100mb Refined Fuel) would require no less than at least 17 Compression Dynamos. probably more (16 just for the jack!). if you wanted to use ALL the pumpjack's output per tick, you would need a whopping 120 Dynamos! that's off a DEPLETED jack! Admittedly you make a power profit of over 900 RF per mb, but that's far too many dynamo's to run. That's why TE dynamo's can be upgraded in the first place. In addition, without the Excitation Field Limiter aug, ALL dynamos burn 5 rf/t of fuel even while on 0 power draw.

My personal suggestion is to implement dynamo upgrades using !tweaked! recipes, to force the players to build higher tiers of infrastructure in order to output more power.

Also, the Redstone Furnace Augments should have their Recipes removed in order to avoid Confusion.
Same for Dynamo Augs if non-upgradability is intentional.

And while I'm at this issue, i REALLY recommend tweaking the Mekanism Configurator to not need 2 Enriched Alloy. It's the only way to manipulate Mekanism cabling, which all have... issues, with cross-mod interaction. As an example, unless you configurate energy cables to force extract, they cannot pull power out of a Calculator Power Cube. Logistical Pipes without configuration are basically Itemducts... without servos. The fact that the infuser is (correctly) locked behind very high progression levels makes pretty much every Mek basic cable useless except for the power one, and even that is weakened dramatically.

Sorry for long-as-hell issue post, data points kept popping up and I've been adding them into the initial post.

**Comment by superfluke** [comment]
I appreciate the report. Non-upgradeable dynamos was not intended. Seems like TE config was messing with how upgrades work. Fixed:
1. Dynamos are now upgradeable
2. Redstone furnace augments are removed and hidden
3. Configurator is now craftable with steel and lapis

**Comment by Thornstromb** [comment]
.... quick addition on this topic, is it also intentional that most of the TE machines (not just dynamos) cannot be upgraded at all? its not as crippling for non-dynamo's as machine blocks have 1 aug slot at basic, but im wondering if that is in fact intentional. I should note that having experienced both TE and Mek endgame, Mek machines with full speed/power and even first level factory upgrade (let alone max tier!) utterly stomp TE machines if that is the worry.

examples of machines that would be useful to have upgrades on, and why, so you can decide:
Pulverizer - its really, reaaaaaaaly slow at basic tier. If its supposed to replace lower-tier crushing tech, its almost painful to use.
Sawmill - aside from wood use, is a key component to making a Tree Oil dynamo system.
Induction Smelter - The only way to make hardened glass and Tungsten, ever. Even once you get mek, you still have to use this one.
Compactor - makes coins, partially replaces metal press. like the IS, has No Mek Equivalent.
Magma Crucible - NME.
Fractioning Still - Also NME, and key aspect to making either Tree Oil or Refined Fuel-based power systems.
Centrifugal Seperator - NME, core progression machine

its kind of odd that the only machine that has a functional upgrade recipe and is actually useful to do so with is the Phytogenic Insulator (for selfcontained tree farm.... somehow. trying to auto-gen PhytoGro is.... ow.)

**Comment by superfluke** [comment]
You should be able to upgrade them. I haven't had that problem with te machines. You are trying to upgrade them by right clicking with the upgrade kit in world, correct? Either way, the config option that was messing with dynamos also affects other te machines, so next version upgrading should be more reliable.
