### ISSUE TITLE
AS Lens Crash

### ISSUE THREAD

**Issue by Thornstromb** [superfluke/undiscovered#53]
https://github.com/HellFirePvP/AstralSorcery/issues/537 see here, note author response.

could be caused by outdated version, but judging by response wording there's something wrong with the way the pack is handling the recipe, losing the metadata that's supposed to pass from the rock crystal you use. can confirm that creative-generated lens work perfectly.

If you can pinpoint the origin of the error, id recommend checking the Collector Crystals (both kinds) and also the Prism to make sure the same thing hasn't happened to them.

CONFIRMED : a celestial collector crystal just crashed the server same way lens did. Were having trouble booting the server now. will inform whether this bug killed the world completely or not when we know more.

**Comment by superfluke** [comment]
The lens crash was certainly a problem with my output not having nbt. Next version the lenses wont crash, but I'll have to see if I can get the nbt to transfer from crystal to lens properly. 

As for the prism and collector crystals, I have not changed either of those recipes. You're welcome to post the crash log for me to take a look at, but the collector crystals shouldn't have the same problem the lens does.

**Comment by Thornstromb** [comment]
oddities. well we fixed the server, and still don't know why the crystal glitched then. not sure what to tell you on the recipe NBT. maybe try to see how AS basecode handles it?

Thanks once more. we've been making steady progress through this pack, so we've been finding plenty of little hiccups along the way.

as a minor suggestion, maybe look into Ender Compass to make the everpresent nightmare of locating the first Fortress less of a hassle?

**Comment by superfluke** [comment]
Well as fixed as this issue is gonna get unless AS dev adds in more support for craft tweaker functions.

Also check out the RandomThings artificial end portal if you're already that far down the magic tree that you can make the end rods with AS collector crystals: https://randomthingsminecraftmod.wikispaces.com/Artificial+End+Portal
