### ISSUE TITLE
Crash upon handing in Craftsman 5

### ISSUE THREAD

**Issue by pie-flavor** [superfluke/undiscovered#59]
https://gist.github.com/pie-flavor/9c86bc600d9575ed13a0c19ac7d7a839

**Comment by superfluke** [comment]
I've had multiple people go through this quest and that's the first I've seen it crash. I would try using the BQM update item or running the command `/bq_admin default load` and see if resyncing your quests fixes things.

**Comment by pie-flavor** [comment]
It was a brand new install, and it doesn't seem to be repeating itself. Still, heck of a bug.

**Comment by superfluke** [comment]
Weird, but BQM isn't 100% stable on 12.2. Looks like funwayguy has started updating again tho, so might see some improvements in the future.
