### ISSUE TITLE
Redstone ore overworld generation disabled?

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#6]
Don't know if it's intentional but in 00_minecraft.json it seems as dimension 0 is on a blacklist for"redstone_otherdim" (line 223) even though the section above it allows redstone in dimension 0 (line 202).

**Comment by superfluke** [comment]
Yes this is intended. Line 202 allows for very rare generation of redstone ore in the overworld. Line 223 blocks normal redstone generation in the nether, overworld, and end but allows for normal generation in other dimensions (such as the beneath or rftools).

**Comment by Ozzymud** [comment]
I have 4 stacks of diamonds from manual mining(no fortune), a lot of destabilized clathrate, but not a single piece of redstone ore... seems either too rare or non-existant.

**Comment by superfluke** [comment]
Redstone ore is very, very rare. You can process your clathrate into redstone, create redstone with a blood infuser and dull dust, or processing the scrapped electronics found in lost cities.

**Comment by Ozzymud** [comment]
Fair enough, so no "scavenge for iron" like every other pack... instead scavenge for redstone.
