### ISSUE TITLE
Mod request: Akashic Tome and Morph-o-Tool

### ISSUE THREAD

**Issue by pie-flavor** [superfluke/undiscovered#60]
Especially AT.

**Comment by superfluke** [comment]
Like the idea of morph-o-tool but still has some oddities that bug me. Doesn't work with IE or mek and if you combine the magneticraft crushing hammer you can destroy the entire set of tools by using it on the crushing table. 
Akashic tome is really cool tho, didn't know that existed. Seems to work well with even with BQM book and the AS books inventory. I'll add that to the next version.

**Comment by pie-flavor** [comment]
Yeah I guess I wasn't thinking about the tools which have durability and other data.
By the way, why isn't Quark in here?

**Comment by superfluke** [comment]
Lots of features added by quark that I like are already covered by other mods in the pack (inventory tweaks, morpheus, ftbu, default world options). The few options I would use from quark don't seem worth the bloat of all the extra decorative blocks.
