### ISSUE TITLE
Survivalist Generator not a valid option to complete quest "T0 Power"

### ISSUE THREAD

**Issue by tommyTT** [superfluke/undiscovered#64]
Maybe I'm missing something but I have the following problem with the quest for the ExU Survivalist Generator. It seems to me that it is not a valid way to complete the "T0 Power" section in the "Powered" quest line. In order to craft the generator, you require Reinforced Stone. For that you need the Calculator, which requires a Calculator Assembly that uses a Basic Circuit Board. That circuit is made in the centrifuge with tin plates, but the only way to get tin plates is with the IE Metal Press and in order to run that machine you need to power it somehow. You could to that with the clockwork engine or the hand cranked generator, but that would already complete that stage of the quest line. 
The amount of work to reach this point seems unproportional to the other options and once you have a carpenter and a way to power it, the IE water wheels or the peat fired engine are right around the corner, so I see no need to craft the survivalist generator at all.

I can think of a few possible solutions to include the generator in the quest lines:

1. Make it a base component for something else (e.g. the ExU Furnace Generator instead of the Electric Furnace).
2. Make it not take reinforced stone but something like IE concrete instead (it is required for the calculator anyways).

Regards,
Tommy

**Comment by superfluke** [comment]
I did want other power options to seem more attractive compared to the survival gen, but I agree stable stone is a bit too far into progression. Changed to leaded concrete next version, so players will need the crushing table to craft it, but no rf is needed.

**Comment by tommyTT** [comment]
That‘s a good change and would make it a reasonable option for that quest line. Thanks for the quick response.
