### ISSUE TITLE
Broken Recipes

### ISSUE THREAD

**Issue by PricklyPorcupine** [superfluke/undiscovered#67]
These two recipes both appear in JEI but don't appear to work in version 2.7.

1. Undead Log to Holy Wood
Placing a Log (or growing an Undead Tree) next to the Pure Daisy does not generate any particle effects and does not result in Holy Wood being formed.

2. Lava Charm to Blaze Powder
Once the Lava Charm is placed on the Crushing Table, any right click will return it to the inventory, even while holding any of the three Hammers from Magneticraft.

**Comment by superfluke** [comment]
1. An update to botania's custom recipes means that pure daisy check meta data. This means the logs will only convert to holy wood if you place them on their sides with the exposed ends facing east-west. Next update the recipe won't be picky about how the log is placed.

2. I'll have to look into this one
