### ISSUE TITLE
Redstone furnace uncraftable

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#7]
Starmetal ore can be processed on the Crushing Table then put in the sluice box to get Astral Starmetal Chunk... the only usage for this in JEI is to make an ingot in the Redstone Furnace, but the furnace is not craftable(line 27 of thermal.zs)

**Comment by superfluke** [comment]
Looks like JAOPCA added in astral star metal in an update and I didn't notice. Fixed next update.
