### ISSUE TITLE
Luminous Crafting items unavailable

### ISSUE THREAD

**Issue by snowfiend** [superfluke/undiscovered#72]
Pack version 2.11.0
Attempting to create "resonating wand" and "luminous crafting table" at the workbench located 2 blocks below the "collector crystal" yields no craftable objects. Cheated in a luminous crafting table; same items seem to be uncraftable. Other items ("parchment") can be crafted.

**Comment by snowfiend** [comment]
Restarting the pack does not fix the bug in this case. Strangely, another world i created using a previous version does not have this problem. I can switch saves, craft these components on the old one, then switch back to my current world, and the same recipes do not work.

**Comment by superfluke** [comment]
You could probably create a new world on the same version as the buggy world and not have a problem. Here's the more elaborate fix, let me know if this works.
1. Close the game
2. Open the astralsorcery.cfg
3. Change performNetworkIntegrityCheck (line 184ish) to true
4. Reopen game and load world
5. Close game and change performNetworkIntegrityCheck back to false
6. Profit

**Comment by snowfiend** [comment]
Thanks for the help. It appears that the crystal collector I was using was not working. I located another in game, which did. The mod's in game doc doesn't mention any specific criteria which would make one table work and not another.

**Comment by superfluke** [comment]
They should all work for making the resonating wand, that bug has been reported a few times to the devs but they haven't found the root cause of it yet. Running the network check config I mentioned above should fix that buggy crystal for you though.
