### ISSUE TITLE
Creative Tank can be crafted using empty gas tanks.

### ISSUE THREAD

**Issue by BlueAgent** [superfluke/undiscovered#78]
![Creative Tank recipe with empty tanks](https://i.imgur.com/QcKom0P.png)

Seems to be ignoring the nbt on the tanks, empty basic gas tanks work as well.

Undiscovered 2.14.1

**Comment by MelanX** [comment]
It’s an Extended Crafting bug. If you update to the newest version (and Cucumber as well) it should be fixed.

**Comment by BlueAgent** [comment]
Closing as MelanX mentioned it should just require an update to extended crafting, which would probably be done the next time the pack is updated.
