### ISSUE TITLE
Retrieval versus crafting quests

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#8]
Several times now I have had to backtrack or create extra(sure i will use them) stuff. Coke bricks, blast bricks, petal apothecary have all had to be picked back up in world, only minor annoyances like the coke oven was still full of creosote and I had to make treated wood before breaking it.

I noticed ?all? the quests are type "retrieval", other pack i have played I believe there is a "crafting" variant. If I got excited when something opened up and crafted a whole bunch of stuff it would still recognize in the book without having to get it back in my inventory.

**Comment by superfluke** [comment]
Changing them to 'crafting' quests would mean you would have to wait until the quest is unlocked and then craft the needed items. So you wouldn't be able to just pick up the coke bricks, you'd have to craft a whole new set.
You might be thinking of how HQM worked in 1.7.10 which would detect retrieval quests even if you hadn't unlocked them yet. Not anything I can do to change that behavior in BQ though.

**Comment by Ozzymud** [comment]
This to me sounds like a quest structuring issue. I have played several "hqm" style packs that use Better Questing in 1.10 and 1.12 now, this is the 1st pack that has had this annoyance. Maybe because the other packs were indeed more linear and I was unable to craft stuff like the coke bricks before the quest was available. Some packs have detection on coal coke, as besides the village huts, you pretty much need to get a coke oven beforehand. At the very least detect a bucket of creosote, as afaik that is not obtainable through "luck". Same for the Blast Furnace, detect some amount of steel. For stuff like the scarecrow change the recipe to require something I shouldn't have before the quest comes along... maybe make it require some treated materials (so it don't rot in the weather). For the AA iron casing, it already needs the circuit and quartz plate so detect those or something else because most players as soon as they create an iron casing are gonna use it I think (not a huge deal on items like that one as more will likely be created).
