### ISSUE TITLE
End + Dragon issues

### ISSUE THREAD

**Issue by ghost** [superfluke/undiscovered#81]
I'm not entirely sure if this is a bug as it's possible this content has been gated or perhaps a mod changes behaviour?

Currently, my players are stuck in the end. The dragon has, from what I can tell, failed to spawn. This means because the dragon can't be killed, everyone in the end is stuck there. As the admin I teleported to the overworld and then discovered that the end portal no longer functions. Restarting the server fixed the portal but the dragon still had not spawned. Manually spawning it in results in it being unharmable and stationary.

Not really sure what else can be done to try and solve this. Any ideas would be appreciated.

We're running 2.14.1. Nothing removed or added.

**Comment by superfluke** [comment]
Not intended behavior. Looks like a bug with forge. A solution seems to be editing the DragonKilled flag in the level.dat and deleting the dim-1 folder to reset the end. 

>  For some reason my level.dat file had DragonKilled 1 before I even entered the dimension. I manually set it back to zero and deleted the end dimension world folder (DIM1) to fix it.

There's a more extensive discussion about the same issue here: https://github.com/DarkPacks/SevTech-Ages/issues/1575

**Comment by ghost** [comment]
Good to know! I'll go ahead and close the issue.
