### ISSUE TITLE
Slightly increase rate of "loose screws"

### ISSUE THREAD

**Issue by Ozzymud** [superfluke/undiscovered#9]
I have opened quite a few of the scrap piles. I have components to make various plates and gears, but they are kinda useless as I've only received enough loose screws to assemble one plate or gear: 
![image1](https://user-images.githubusercontent.com/6426344/34049493-706a951c-e16c-11e7-8e02-dba6f6bcec3d.png)

Suggest increasing the rate for loose screws so this stuff aint just sitting in a crate being useless.

**Comment by superfluke** [comment]
Very minor increase but now also found randomly in lost city/dungeon chests.
